version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JIRA_URL: "${JIRA_URL}"
      JIRA_QUERY: "${JIRA_QUERY}"
      GITLAB_URL: "${GITLAB_URL}"
      GITLAB_PROJECT: "${GITLAB_PROJECT}"
      JIRA_TOKEN: "${JIRA_TOKEN}"
      JIRA_LOGIN: "${JIRA_LOGIN}"
      GITLAB_TOKEN: "${GITLAB_TOKEN}"
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.0.0/16
